# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x_vC1Vopc25lO04HnXmYlZEuUN6_UnHr
"""

def add(a, b):
    return a + b


def subtract(a, b):
    return a - b


def multiply(a, b):
    return a * b


def divide(a, b):
    if b == 0:
        return "Error! Division by zero is not allowed."
    return a / b


def display_menu():
    print("\n===== Calculator =====")
    print("1. Addition (+)")
    print("2. Subtraction (-)")
    print("3. Multiplication (*)")
    print("4. Division (/)")
    print("5. Exit")


while True:
    display_menu()

    choice = input("Enter your choice (1-5): ")

    if choice == "5":
        print("Thank you for using the calculator!")
        break

    if choice not in ["1", "2", "3", "4"]:
        print("Invalid choice! Please try again.")
        continue

    try:
        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))
    except ValueError:
        print("Please enter valid numeric values.")
        continue

    if choice == "1":
        print(f"Result = {add(num1, num2)}")

    elif choice == "2":
        print(f"Result = {subtract(num1, num2)}")

    elif choice == "3":
        print(f"Result = {multiply(num1, num2)}")

    elif choice == "4":
        print(f"Result = {divide(num1, num2)}")