# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aFW48xNyIECq5FMqDWyBLwAO21c8Mx5U
"""

import os

FILENAME = "tasks.txt"


def load_tasks():
    """Load tasks from the text file."""
    if not os.path.exists(FILENAME):
        return []

    with open(FILENAME, "r") as file:
        tasks = [line.strip() for line in file.readlines()]

    return tasks


def save_tasks(tasks):
    """Save all tasks to the text file."""
    with open(FILENAME, "w") as file:
        for task in tasks:
            file.write(task + "\n")


def view_tasks(tasks):
    """Display all tasks."""
    if not tasks:
        print("\nNo tasks available.\n")
        return

    print("\nYour Tasks:")
    for index, task in enumerate(tasks, start=1):
        print(f"{index}. {task}")
    print()


def add_task(tasks):
    """Add a new task."""
    task = input("Enter new task: ")

    if task.strip() == "":
        print("Task cannot be empty.")
        return

    tasks.append(task)
    save_tasks(tasks)
    print("Task added successfully.")


def remove_task(tasks):
    """Remove a task."""
    view_tasks(tasks)

    if not tasks:
        return

    try:
        task_number = int(input("Enter task number to remove: "))

        if 1 <= task_number <= len(tasks):
            removed = tasks.pop(task_number - 1)
            save_tasks(tasks)
            print(f'"{removed}" removed successfully.')
        else:
            print("Invalid task number.")

    except ValueError:
        print("Please enter a valid number.")


def menu():
    print("\n====== TO-DO LIST ======")
    print("1. View Tasks")
    print("2. Add Task")
    print("3. Remove Task")
    print("4. Exit")


def main():
    tasks = load_tasks()

    while True:
        menu()

        choice = input("Enter your choice (1-4): ")

        if choice == "1":
            view_tasks(tasks)

        elif choice == "2":
            add_task(tasks)

        elif choice == "3":
            remove_task(tasks)

        elif choice == "4":
            print("Thank you for using the To-Do List App!")
            break

        else:
            print("Invalid choice. Please try again.")


if __name__ == "__main__":
    main()