# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X1XyfYLJr1YFgAva7S6W31hQrUSZitMz
"""

import requests
from bs4 import BeautifulSoup

URL = "https://www.bbc.com/news"


def fetch_headlines():
    headers = {
        "User-Agent": "Mozilla/5.0"
    }

    response = requests.get(URL, headers=headers)

    if response.status_code != 200:
        print("Failed to fetch webpage.")
        return []

    soup = BeautifulSoup(response.text, "html.parser")

    headlines = []

    # Find all h2 tags
    for tag in soup.find_all("h2"):
        text = tag.get_text(strip=True)

        if text and text not in headlines:
            headlines.append(text)

    return headlines


def save_headlines(headlines):
    with open("headlines.txt", "w", encoding="utf-8") as file:
        for i, headline in enumerate(headlines, start=1):
            file.write(f"{i}. {headline}\n")


def main():
    headlines = fetch_headlines()

    if headlines:
        print("\nTop Headlines\n")

        for i, headline in enumerate(headlines, start=1):
            print(f"{i}. {headline}")

        save_headlines(headlines)

        print("\nHeadlines saved successfully in headlines.txt")

    else:
        print("No headlines found.")


if __name__ == "__main__":
    main()